os: linux
language: java
jdk:
  - openjdk8
sudo: required
env: DISPLAY=':99.0'
dist: trusty
addons:
  chrome: stable
before_script:
  - sh -e /etc/init.d/xvfb start
script:
  - ./gradlew test --debug
